cacheFolder: .yarn/cache

cacheMigrationMode: always

changesetIgnorePatterns:
  - "**/__tests__/**"
  - "**/*.test.{js,ts}"

checksumBehavior: update

compressionLevel: mixed

enableColors: true

enableConstraintsChecks: true

enableGlobalCache: false

enableHyperlinks: true

enableNetwork: true

enableProgressBars: true

enableScripts: true

pnpEnableEsmLoader: true

pnpMode: strict

nodeLinker: pnpm
